### ISSUE TITLE
'SleepInvocation' object has no attribute 'workflow'

### ISSUE THREAD

**Issue by billtran1632001** [ymgenesis/NodeUtilities#1]
The Sleep node currently doesn't work with InvokeAI 3.4.0post2.

```
  File "/stuff/AI/Images/Tools/InvokeAI/.venv/lib/python3.11/site-packages/invokeai/app/services/invocation_processor/invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stuff/AI/Images/Tools/InvokeAI/.venv/lib/python3.11/site-packages/invokeai/app/invocations/baseinvocation.py", line 599, in invoke_internal
    return self.invoke(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/stuff/AI/Images/Tools/InvokeAI/.venv/lib/python3.11/site-packages/invokeai/app/invocations/sleep.py", line 51, in invoke
    workflow=self.workflow,
             ^^^^^^^^^^^^^
  File "/stuff/AI/Images/Tools/InvokeAI/.venv/lib/python3.11/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SleepInvocation' object has no attribute 'workflow'

[2023-12-22 22:47:58,987]::[InvokeAI]::ERROR --> Error while invoking:
'SleepInvocation' object has no attribute 'workflow'
```
